Newbranch lea
LeandroOnline/news pull request #1
Opened 2022-12-21 15:49 UTC by LeandroOnline

hice la configuracion del top o navbar, estoy avanzando en las subdivisiones

2022-12-21 16:37 UTC, neriheredia requested changes

2022-12-21 16:37 UTC, neriheredia commented on src/Page/Top/components/Right/Right.jsx
> +				<i className='fa-solid fa-magnifying-glass'></i>
Se podría cerrar de esta manera, ya que no vas a poner nada de texto dentro de la etiqueta
<i className='fa-solid fa-magnifying-glass' />

2022-12-21 16:37 UTC, neriheredia commented on src/Page/Top/components/Left/Left.jsx
> +			<i className='fa-brands fa-square-twitter'></i>
Lo mismo aquí, se podría cerrar en el primer tag, no es necesario el segundo

2022-12-21 16:37 UTC, neriheredia commented on src/Page/Top/Top.module.css
> +}
Acomodar las propiedades en orden alfabético y borrar el espacio de sobra

2022-12-21 16:37 UTC, neriheredia commented on index.html
>  		<style>
Los scripts deben agregarse en el body, y en este caso no sería necesario, ya que hay un link apuntando a la librería de fontawesome para los iconos

2022-12-21 19:44 UTC, neriheredia requested changes

2022-12-21 19:44 UTC, neriheredia commented on index.html
> +		></script>
Esto debes borrarlo

2022-12-22 12:06 UTC, closed without merging

2022-12-22 12:06 UTC, LeandroOnline commented
PR no necesario