New structure
LeandroOnline/news pull request #2
Opened 2022-12-22 10:51 UTC by LeandroOnline

I did the new structure, but i did't find the loup icon

2022-12-22 13:13 UTC, neriheredia requested changes

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Right/Right.jsx
> +			{/* topIcon fab fa-twitter-square */}
eliminar comentario

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Right/Right.jsx
> +	return (
dejar una linea en blanco en medio

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Left/Left.jsx
> +
borrar lo comentado

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Center/Center.jsx
> +function Center() {
dejar un espacio en blanco

2022-12-22 13:13 UTC, neriheredia commented on src/App.jsx
> +			{/* </Routes> */}
Borrar lo comentado, ¿y por qué un <hr />?

2022-12-22 13:13 UTC, neriheredia commented on index.html
> +		<!-- algo -->
borrar comentario

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Top.module.css
> +a {
dejar un espacio en blanco en el medio

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Top.module.css
> +	font-weight: 300;
orden alfabetico

2022-12-22 13:13 UTC, neriheredia commented on src/Pages/Home/Home.jsx
> +export default Home;
dejar una línea en blanco en el medio y al final del componente

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Top.jsx
> +export default Top;
dejar una línea en blanco en el medio y al final del componente

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Right/Right.module.css
> +.right :hover {
dejar un espacio en medio

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Right/Right.jsx
> +export default Rigth;
dejar una línea en blanco en el medio y al final del componente

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Left/Left.jsx
> +export default Left;
dejar una línea en blanco en el medio y al final del componente

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Navbar/Center/Center.jsx
> +export default Center;
dejar una línea en blanco en el medio y al final del componente

2022-12-22 13:13 UTC, neriheredia commented on src/Components/Header/Header.jsx
> +export default Header;
dejar una línea en blanco en el medio y al final del componente

2022-12-22 18:21 UTC, LeandroOnline commented
Realice las correcciones

2022-12-22 22:42 UTC, LeandroOnline commented
Todo listo

2022-12-22 23:10 UTC, neriheredia commented on index.html
> +		<!-- algo -->
@LeandroOnline esto te falta hacer

2022-12-23 14:33 UTC, neriheredia requested changes

2022-12-23 14:33 UTC, neriheredia commented on src/Components/Navbar/Navbar.module.css
> +}
Orden alfabético

2022-12-23 14:33 UTC, neriheredia commented on src/Components/Navbar/Right/Right.jsx
> +			{/* topIcon fab fa-twitter-square */}
Eliminar comentario

2022-12-23 14:46 UTC, neriheredia requested changes

2022-12-23 14:46 UTC, neriheredia commented on src/Components/Navbar/Navbar.module.css
> +}
la Clase también debe ir en orden alfabetico

2022-12-23 14:46 UTC, neriheredia commented on src/Components/Navbar/Right/Right.module.css
> +}
Aqui también

2022-12-23 20:48 UTC, LeandroOnline commented on src/Components/Navbar/Right/Right.jsx
> +			{/* topIcon fab fa-twitter-square */}
es raro pero ya habia hecho el push sin el comentario

2022-12-23 22:42 UTC, neriheredia approved these changes
Excelente

2022-12-24 01:04 UTC, merged