New structure
LeandroOnline/news pull request #4
Opened 2022-12-27 17:56 UTC by LeandroOnline

Organice por abc
cree rutas
cree componentes pero sin logica, solo para organizar las rutas
arregle el css que me daba un poco para la izquierda el navbar

2023-01-02 17:53 UTC, heredialucas commented on src/Pages/Write/Write.jsx
> +export default Write;
Trataría de ponerle nombres más declarativo a los archivos creados, "Left", "Center", etc. No dicen mucho de lo q representan en si.

2023-01-02 17:58 UTC, heredialucas commented on src/Pages/Write/Write.jsx
> +export default Write;
En que basaste tu decisión para usar module dentro de los componentes hijos, y no en los componentes padre? Por ejemplo en NavBar.jsx y sus componentes hijos

2023-01-02 17:59 UTC, heredialucas commented on src/Pages/Write/Write.jsx
> +export default Write;
Agregaría a tu estructura un archivo con tamaños, fuentes, colores,etc. Para poder tenes estandarizado eso antes de que la app crezca y se vaya complicando cada vez mas hacerlo.

2023-01-02 18:02 UTC, heredialucas commented on src/Components/Navbar/Right/Right.css
> +	gap: 10px;
órden alfabético

2023-01-02 18:06 UTC, heredialucas commented on src/Pages/Write/Write.jsx
> +export default Write;
No corresponde el diseño presentado con el deseado 
![Captura de pantalla_20230102_150511](https://user-images.githubusercontent.com/77968538/210266067-81f000b0-eb5b-4c3d-a37e-c4f9af459d71.png)

2023-01-02 18:08 UTC, heredialucas requested changes
Con comentarios

2023-01-03 10:37 UTC, LeandroOnline commented on src/Pages/Write/Write.jsx
> +export default Write;
podria cambiarles los nombres a socialicons -- menu -- entry

2023-01-03 10:37 UTC, LeandroOnline commented on src/Pages/Write/Write.jsx
> +export default Write;
no entendi esto, tengo entendido que module es una forma de dar estilo, pero no lo encontre asi definido en mi proyecto

2023-01-03 10:40 UTC, LeandroOnline commented on src/Pages/Write/Write.jsx
> +export default Write;
voy a necesitar ayuda con esto, las fuentes pense que se descargaban con el link o script en el html, no sabia que se podia poner en una carpeta

2023-01-03 10:41 UTC, LeandroOnline commented on src/Components/Navbar/Right/Right.css
> +	gap: 10px;
listo

2023-01-03 10:42 UTC, LeandroOnline commented on src/Pages/Write/Write.jsx
> +export default Write;
ok, solucionado

2023-01-03 11:03 UTC, LeandroOnline commented on src/Pages/Write/Write.jsx
> +export default Write;
le puse esos nombres porque los vi asi en el inspector del blog a copiar

2023-01-03 12:20 UTC, LeandroOnline commented
estaba trabajando sobre una nueva rama donde puse todo en contexto, procedo a cerrar este PR?

2023-01-06 17:33 UTC, closed without merging